import type {
  ActiveRecommendationPriceFreshness,
  AlertDestination,
  AuthRbac,
  BenchmarkDriftQuality,
  CycleAiQualityAudit,
  DataOperationsArtifactRunner,
  LiveAiInvocationHealth,
  LocalIngestWorker,
  ManualIngestSmoke,
  NewsAiEvalQuality,
  OpenAiProviderHealth,
  OutcomeMaturityWaitMonitor,
  PortfolioReviewDecisionFeedback,
  PortfolioReviewDecisionHistory,
  PortfolioReviewFeedbackActionRouter,
  PortfolioReviewFeedbackCadence,
  PortfolioReviewFeedbackCalibration,
  ProductionApiServer,
  ProfessionalAnalysisDepth,
  ProfessionalAnalysisNextAction,
  ProfessionalAnalysisQuality,
  ProfessionalRecommendationCoverageAudit,
  ProfessionalSourceGapPrioritization,
  ProfileSchedulerStatus,
  RecommendationOutcomeCalibration,
  RecommendationOutcomeDueActionRouter,
  RecommendationOutcomeMaturity,
  RecommendationWeightReviewReadiness,
} from "./dataHealthTypes";

export const DEFAULT_MANUAL_SMOKE: ManualIngestSmoke = {
  status: "not_configured",
  execute: false,
  generated_at: "",
  runtime_status: "",
  artifact_root: "",
  job_count: 0,
  planned_job_ids: [],
  artifact_runs: [],
  failed_job_count: 0,
  next_actions: ["run manual-local-ingest-smoke --output outside the repository"],
  source: "not_configured",
};

export const DEFAULT_LOCAL_WORKER: LocalIngestWorker = {
  status: "not_configured",
  execute: false,
  generated_at: "",
  completed_cycle_count: 0,
  failed_cycle_count: 0,
  max_cycles: 0,
  interval_seconds: 0,
  stop_on_failure: true,
  job_ids: [],
  latest_smoke_output_path: "",
  cycles: [],
  next_actions: ["run local-ingest-worker-run --output outside the repository"],
  source: "not_configured",
};

export const DEFAULT_CYCLE_AI_QUALITY_AUDIT: CycleAiQualityAudit = {
  status: "not_configured",
  execute: false,
  generated_at: "",
  as_of_date: "",
  lookback_days: 0,
  audit_score: 0,
  issue_count: 0,
  readiness_gap_count: 0,
  readiness_gaps: [],
  metrics: {},
  checks: {},
  samples: {},
  next_actions: ["cycle-ai-quality-audit-run 실행 결과를 연결한다."],
  source: "not_configured",
};

export const DEFAULT_NEWS_AI_EVAL_QUALITY: NewsAiEvalQuality = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "news_ai_extraction_quality",
  dataset_version: "news-ai-eval-v1",
  provider: "fixture",
  model_name: "news-ai-eval-fixture-v1",
  overall_pass: false,
  case_count: 0,
  passed_case_count: 0,
  failed_case_count: 0,
  theme_precision: 0,
  direct_ticker_grounding_precision: 0,
  macro_only_false_ticker_rate: 0,
  macro_only_false_ticker_count: 0,
  quantum_energy_misclassification_count: 0,
  blocked_candidate_correctness: 0,
  korean_translation_availability: 0,
  metrics: {},
  pass_thresholds: {},
  case_results: [],
  next_action: "news-ai-eval-run --provider fixture --execute를 실행해 기준 정답 뉴스 세트 회귀평가를 저장한다.",
};

export const DEFAULT_LIVE_AI_INVOCATION_HEALTH: LiveAiInvocationHealth = {
  status: "missing_recent_invocations",
  attention_required: true,
  window_hours: 48,
  recent_invocation_count: 0,
  recent_success_count: 0,
  recent_failed_count: 0,
  critical_failed_count: 0,
  critical_success_count: 0,
  latest_unhealthy_count: 0,
  critical_latest_unhealthy_count: 0,
  latest_invocation_at: "",
  latest_failed_at: "",
  latest_failed_task_name: "",
  latest_error_summary: "",
  latest_error_code: "",
  task_health: [],
  next_action: "최근 실제 AI 호출 증거가 없다. 뉴스 AI 배치가 실제로 호출됐는지 본다.",
};

export const DEFAULT_OPENAI_PROVIDER_HEALTH: OpenAiProviderHealth = {
  status: "missing_api_key",
  label: "OpenAI 키 없음",
  balance_known: false,
  balance_check_method: "not_available",
  remaining_balance_usd: null,
  api_key_configured: false,
  admin_api_key_configured: false,
  last_checked_at: "",
  next_retry_at: "",
  fallback_provider: "codex_oauth",
  local_fallback_provider: "local_rules",
  message: "OpenAI provider 상태를 아직 읽지 못했다. 예비 provider를 사용한다.",
  cost_status: {
    report_name: "openai_admin_cost_status",
    status: "admin_key_missing",
    cost_known: false,
    admin_api_key_configured: false,
    lookback_days: 7,
    total_cost_usd: null,
    latest_day_cost_usd: null,
    currency: "usd",
    period_start: "",
    period_end: "",
    last_checked_at: "",
    error_code: "",
    message: "Admin Costs API key가 없어 비용 조회를 실행할 수 없다.",
    billing_overview_url: "https://platform.openai.com/settings/organization/billing/overview",
    secret_free: true,
  },
};

export const DEFAULT_BENCHMARK_DRIFT_QUALITY: BenchmarkDriftQuality = {
  status: "missing_guardrail",
  guardrail_status: "missing",
  guardrail_eval_run_id: "eval-run-unknown",
  guardrail_as_of_date: "",
  drift_status: "missing",
  drift_calculated: false,
  benchmark_code: "",
  benchmark_source: "",
  source_type: "",
  source_as_of_date: "",
  source_age_days: null,
  component_count: 0,
  composition_coverage_weight: 0,
  active_share: null,
  total_absolute_drift: null,
  top_active_positions: [],
  outlier_positions: [],
  outlier_decisions: [],
  review_candidate_count: 0,
  review_decision_counts: {},
  attention_required: true,
  managed_review_status: "source_or_guardrail_gap",
  managed_review_reason: "위험 예산 평가가 아직 없어 벤치마크 drift 관리 상태를 판단할 수 없다.",
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
  checks: [],
  next_actions: ["portfolio-risk-budget-guardrail-run을 먼저 실행한다."],
};

export const DEFAULT_PORTFOLIO_REVIEW_DECISION_HISTORY: PortfolioReviewDecisionHistory = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "portfolio_review_decision_history",
  dataset_version: "portfolio-review-decision-history-v1",
  as_of_date: "",
  portfolio_name: "Long Term Paper",
  source_portfolio_coverage_as_of_date: "",
  coverage_measurement_end_date: "",
  decision_status: "missing",
  decision_count: 0,
  review_required_count: 0,
  benchmark_decision_count: 0,
  position_sizing_decision_count: 0,
  decision_counts: {},
  attention_required: true,
  managed_review_status: "unmanaged_or_missing",
  managed_review_reason: "검토 이력, 안전 조건, 또는 후속 실행 분기 상태 확인이 필요합니다.",
  top_decision: null,
  latest_decisions: [],
  guardrails: {
    recommendation_scoring_mutated: false,
    benchmark_definition_mutated: false,
    portfolio_position_mutated: false,
    automatic_rebalance_allowed: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
    order_boundary: "read_only_no_order",
  },
  next_action: "portfolio-review-decision-history-run을 실행해 최신 포트폴리오 검토 결정을 이력화한다.",
};

export const DEFAULT_PORTFOLIO_REVIEW_DECISION_FEEDBACK: PortfolioReviewDecisionFeedback = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "portfolio_review_decision_outcome_feedback",
  dataset_version: "portfolio-review-decision-outcome-feedback-v1",
  as_of_date: "",
  portfolio_name: "Long Term Paper",
  source_history_eval_run_id: "eval-run-unknown",
  source_history_as_of_date: "",
  min_horizon_days: 30,
  history_age_days: 0,
  feedback_status: "missing",
  decision_count: 0,
  too_early_count: 0,
  validated_count: 0,
  contradicted_count: 0,
  needs_more_data_count: 0,
  status_counts: {},
  paper_validation: {
    paper_validation_run_id: "paper-validation-unknown",
    validation_date: "",
    status: "missing",
    recommendation_count: 0,
    conflict_count: 0,
    approved_action_count: 0,
  },
  top_feedback: null,
  latest_items: [],
  guardrails: {
    recommendation_scoring_mutated: false,
    benchmark_definition_mutated: false,
    portfolio_position_mutated: false,
    automatic_rebalance_allowed: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
    order_boundary: "read_only_no_order",
  },
  next_action: "portfolio-review-decision-outcome-feedback-run을 실행해 저장된 검토 결정이 후속 성과와 맞는지 본다.",
};

export const DEFAULT_PORTFOLIO_REVIEW_FEEDBACK_CALIBRATION: PortfolioReviewFeedbackCalibration = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "portfolio_review_feedback_calibration",
  dataset_version: "portfolio-review-feedback-calibration-v1",
  as_of_date: "",
  portfolio_name: "Long Term Paper",
  lookback_days: 0,
  min_feedback_runs: 0,
  min_mature_decisions: 0,
  max_contradiction_rate: 0,
  calibration_status: "missing",
  maturity_status: "missing_calibration",
  feedback_run_count: 0,
  decision_count: 0,
  mature_decision_count: 0,
  too_early_count: 0,
  validated_count: 0,
  contradicted_count: 0,
  needs_more_data_count: 0,
  contradiction_rate: 0,
  validated_rate: 0,
  feedback_run_gap: 0,
  mature_decision_gap: 0,
  estimated_maturity_date: "",
  days_until_maturity: null,
  attention_required: true,
  managed_wait: false,
  managed_gate_status: "unmanaged_attention",
  managed_gate_reason: "",
  weight_review_blocked: true,
  weight_review_block_reason: "검토 성과 누적평가 기록이 없어 추천 산식 검토를 막는다.",
  status_counts: {},
  family_summaries: [],
  decision_type_summaries: [],
  symbol_summaries: [],
  latest_feedback_runs: [],
  guardrails: {
    recommendation_scoring_mutated: false,
    benchmark_definition_mutated: false,
    portfolio_position_mutated: false,
    automatic_rebalance_allowed: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
    order_boundary: "read_only_no_order",
  },
  next_action: "포트폴리오 검토 누적평가를 실행해 누적 검토 사후평가 신뢰도를 집계한다.",
  next_calibration_action: "검토 이력과 사후평가를 먼저 누적한다.",
};

export const DEFAULT_PROFESSIONAL_ANALYSIS_NEXT_ACTION: ProfessionalAnalysisNextAction = {
  status: "missing",
  title: "전문 분석 상태 없음",
  summary: "전문 분석 원천 공백, 성과 사후평가, 추천 산식 검토 상태를 아직 읽지 못했다.",
  next_action: "전문 분석 data-health payload를 먼저 생성한다.",
  as_of_date: "",
  source_gap_count: 0,
  source_blocker_count: 0,
  average_coverage_ratio: 0,
  guarded_source_blocked_recommendation_count: 0,
  managed_wait: false,
  weight_review_blocked: true,
  manual_weight_review_allowed: false,
  estimated_maturity_date: "",
  days_until_maturity: null,
  next_symbol: "",
  next_symbol_href: "",
  next_symbol_reason: "",
  readiness_items: [],
  order_boundary: "read_only_no_order",
  automatic_weight_change_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
};

export const DEFAULT_PROFESSIONAL_ANALYSIS_QUALITY: ProfessionalAnalysisQuality = {
  status: "missing",
  title: "전문 분석 품질 상태 없음",
  summary: "재무·피어·밸류에이션·산업·AI 리서치 근거 연결 상태를 아직 읽지 못했다.",
  as_of_date: "",
  active_candidate_count: 0,
  complete_candidate_count: 0,
  source_blocked_count: 0,
  average_coverage_ratio: 0,
  layer_checks: [],
  quality_checks: [],
  next_action: "전문 분석 품질 payload를 먼저 생성한다.",
  manual_weight_review_allowed: false,
  automatic_weight_change_allowed: false,
  recommendation_scoring_mutated: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_PROFESSIONAL_RECOMMENDATION_COVERAGE_AUDIT: ProfessionalRecommendationCoverageAudit = {
  status: "missing",
  title: "추천별 전문 감사 상태 없음",
  summary: "active 추천별 재무·피어·밸류에이션·산업·AI 리서치 연결 상태를 아직 읽지 못했다.",
  as_of_date: "",
  recommendation_count: 0,
  ready_for_review_count: 0,
  coverage_gap_count: 0,
  source_blocked_count: 0,
  paper_validation_pending_count: 0,
  average_coverage_ratio: 0,
  items: [],
  next_action: "추천별 전문 분석 coverage audit payload를 먼저 생성한다.",
  recommendation_scoring_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_PROFESSIONAL_ANALYSIS_DEPTH: ProfessionalAnalysisDepth = {
  status: "missing",
  as_of_date: "",
  active_candidate_count: 0,
  complete_candidate_count: 0,
  source_blocked_count: 0,
  fund_like_candidate_count: 0,
  operating_company_candidate_count: 0,
  average_coverage_ratio: 0,
  weakest_coverage_ratio: 0,
  layer_coverage: [],
  items: [],
  next_action: "활성 추천의 전문 분석 깊이를 먼저 계산한다.",
  recommendation_scoring_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_PORTFOLIO_REVIEW_FEEDBACK_CADENCE: PortfolioReviewFeedbackCadence = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "portfolio_review_feedback_cadence",
  dataset_version: "portfolio-review-feedback-cadence-v1",
  as_of_date: "",
  portfolio_name: "Long Term Paper",
  min_horizon_days: 30,
  cadence_status: "missing",
  action_type: "inspect",
  should_run_now: false,
  should_wait: false,
  wait_until: "",
  command: "포트폴리오 검토 실행 주기를 계산해 다음 사후평가/누적평가 작업을 판단한다.",
  follow_up_command: "",
  label: "검토 사후평가 실행 주기 상태를 먼저 계산한다.",
  reason: "아직 포트폴리오 검토 사후평가 실행 주기 기록이 없다.",
  history: {
    status: "missing",
    eval_run_id: "eval-run-unknown",
    created_at: "",
    as_of_date: "",
    decision_status: "missing",
    decision_count: 0,
    review_required_count: 0,
  },
  feedback: {
    status: "missing",
    eval_run_id: "eval-run-unknown",
    created_at: "",
    as_of_date: "",
    source_history_eval_run_id: "eval-run-unknown",
    source_history_as_of_date: "",
    feedback_status: "missing",
    decision_count: 0,
    too_early_count: 0,
    validated_count: 0,
    contradicted_count: 0,
    needs_more_data_count: 0,
  },
  calibration: {
    status: "missing",
    eval_run_id: "eval-run-unknown",
    created_at: "",
    as_of_date: "",
    calibration_status: "missing",
    feedback_run_count: 0,
    decision_count: 0,
    mature_decision_count: 0,
    too_early_count: 0,
    validated_count: 0,
    contradicted_count: 0,
    needs_more_data_count: 0,
    latest_feedback_run_ids: [],
  },
  evidence: {
    history_age_days: 0,
    decision_count: 0,
    recommendation_link_count: 0,
    recommendation_outcome_count: 0,
    price_evidence_count: 0,
    paper_validation: {
      paper_validation_run_id: "paper-validation-unknown",
      validation_date: "",
      status: "missing",
      recommendation_count: 0,
      conflict_count: 0,
      approved_action_count: 0,
    },
  },
  blocks_weight_review: true,
  recommendation_scoring_mutated: false,
  benchmark_definition_mutated: false,
  portfolio_position_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_rebalance_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
  next_action: "포트폴리오 검토 실행 주기를 계산해 다음 사후평가/누적평가 작업을 판단한다.",
};

export const DEFAULT_PORTFOLIO_REVIEW_FEEDBACK_ACTION_ROUTER: PortfolioReviewFeedbackActionRouter = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "portfolio_review_feedback_action_router",
  dataset_version: "portfolio-review-feedback-action-router-v1",
  as_of_date: "",
  portfolio_name: "Long Term Paper",
  source_cadence_status: "missing",
  source_cadence_eval_run_id: "eval-run-unknown",
  source_cadence_created_at: "",
  source_cadence_as_of_date: "",
  cadence_status: "missing",
  source_action_type: "inspect",
  source_should_run_now: false,
  route_action: "no_op",
  action_status: "missing",
  reason: "아직 포트폴리오 검토 실행 분기 기록이 없다.",
  history_eval_run_id: "eval-run-unknown",
  feedback_eval_run_id: "eval-run-unknown",
  calibration_eval_run_id: "eval-run-unknown",
  source_cadence: {
    as_of_date: "",
    cadence_status: "missing",
    action_type: "inspect",
    should_run_now: false,
    should_wait: false,
    command: "",
    follow_up_command: "",
  },
  child_runner: {
    executed: false,
    report_name: "",
    status: "not_run",
    run_id: "pipeline-run-unknown",
    eval_run_id: "eval-run-unknown",
    feedback_status: "",
    calibration_status: "",
  },
  recommendation_scoring_mutated: false,
  benchmark_definition_mutated: false,
  portfolio_position_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_rebalance_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
  next_action: "포트폴리오 검토 실행 분기를 실행해 실행 주기 판단을 안전한 후속 작업으로 연결한다.",
};

export const DEFAULT_RECOMMENDATION_OUTCOME_CALIBRATION: RecommendationOutcomeCalibration = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  as_of_date: "",
  horizon_days: [],
  quality_status: "unknown",
  sample_status: "unknown",
  recommendation_horizon_count: 0,
  recommendation_count: 0,
  outcome_count: 0,
  outcome_coverage_rate: 0,
  ready_for_backfill_count: 0,
  missing_entry_price_count: 0,
  missing_exit_price_count: 0,
  missing_reason_counts: {},
  component_diagnostic_count: 0,
  next_action: "recommendation-outcome-calibration-sample-expansion-run을 실행한다.",
  recommendation_scoring_mutated: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_RECOMMENDATION_OUTCOME_MATURITY: RecommendationOutcomeMaturity = {
  status: "missing",
  as_of_date: "",
  source_calibration_eval_run_id: "eval-run-unknown",
  horizon_days: [],
  recommendation_horizon_count: 0,
  recommendation_count: 0,
  outcome_count: 0,
  not_due_count: 0,
  ready_for_backfill_count: 0,
  due_today_count: 0,
  overdue_count: 0,
  price_gap_count: 0,
  missing_entry_price_count: 0,
  missing_exit_price_count: 0,
  next_due_date: "",
  next_due_count: 0,
  examples: [],
  cadence_action: {
    status: "inspect_outcome_maturity_state",
    action_type: "inspect",
    scheduler_job_id: "recommendation-outcome-backfill-daily",
    pipeline_name: "recommendation_outcome_calibration_sample_expansion",
    should_run_now: false,
    should_wait: false,
    requires_price_backfill: false,
    wait_until: "",
    command: "stockanalysis-operations recommendation-outcome-calibration-sample-expansion-run --env-file <ENV> --as-of-date <YYYY-MM-DD> --execute",
    label: "성과 측정창 상태를 먼저 본다.",
    reason: "maturity monitor 결과가 아직 없다.",
    blocks_weight_review: true,
    automatic_weight_change_allowed: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
  },
  recommendation_scoring_mutated: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
};

export const DEFAULT_RECOMMENDATION_OUTCOME_DUE_ACTION_ROUTER: RecommendationOutcomeDueActionRouter = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  eval_name: "recommendation_outcome_due_action_router",
  dataset_version: "recommendation-outcome-due-action-router-v1",
  as_of_date: "",
  source_calibration_status: "missing",
  source_calibration_eval_run_id: "eval-run-unknown",
  source_calibration_created_at: "",
  source_calibration_summary: {
    as_of_date: "",
    status: "missing",
    quality_status: "unknown",
    sample_status: "unknown",
    next_action: "",
    recommendation_scoring_mutated: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
    order_boundary: "read_only_no_order",
  },
  route_action: "no_op",
  action_status: "missing",
  reason: "아직 추천 성과 실행 분기 기록이 없다.",
  wait_until: "",
  sample_audit_summary: {
    recommendation_horizon_count: 0,
    recommendation_count: 0,
    outcome_count: 0,
    ready_for_backfill_count: 0,
    not_due_count: 0,
    missing_entry_price_count: 0,
    missing_exit_price_count: 0,
    price_gap_count: 0,
    outcome_coverage_rate: 0,
  },
  missing_reason_counts: {},
  missing_examples: [],
  child_runner: {
    executed: false,
    report_name: "",
    status: "not_run",
    run_id: "pipeline-run-unknown",
    eval_run_id: "eval-run-unknown",
    calibration_status: "",
    quality_status: "",
    sample_status: "",
  },
  recommendation_scoring_mutated: false,
  benchmark_definition_mutated: false,
  portfolio_position_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_rebalance_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
  next_action: "recommendation-outcome-due-action-router-run을 실행한다.",
};

export const DEFAULT_RECOMMENDATION_WEIGHT_REVIEW_READINESS: RecommendationWeightReviewReadiness = {
  status: "missing",
  eval_run_id: "eval-run-unknown",
  created_at: "",
  decision: "missing_recommendation_weight_review_readiness",
  manual_weight_review_allowed: false,
  source_quality_status: "unknown",
  source_eval_run_id: "eval-run-unknown",
  outcome_calibration_status: "missing",
  outcome_calibration_eval_run_id: "eval-run-unknown",
  blocker_code: "missing_recommendation_weight_review_readiness",
  blocker_message: "추천 산식 검토 준비 감사 작업을 실행한다.",
  next_action: "추천 산식 검토 준비 감사 작업을 실행한다.",
  automatic_weight_change_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
};

export const DEFAULT_OUTCOME_MATURITY_WAIT_MONITOR: OutcomeMaturityWaitMonitor = {
  status: "missing",
  title: "성과 성숙 상태 없음",
  summary: "추천 성과와 포트폴리오 사후평가 성숙 상태를 아직 읽지 못했다.",
  next_action: "성과 성숙 데이터 상태 기록을 먼저 생성한다.",
  as_of_date: "",
  recommendation_next_due_date: "",
  recommendation_next_due_count: 0,
  recommendation_maturity_status: "missing",
  recommendation_action_status: "missing",
  recommendation_ready_for_backfill_count: 0,
  recommendation_overdue_count: 0,
  recommendation_price_gap_count: 0,
  portfolio_feedback_maturity_date: "",
  portfolio_feedback_status: "missing",
  portfolio_feedback_run_gap: 0,
  portfolio_mature_decision_gap: 0,
  earliest_action_date: "",
  wait_item_count: 0,
  wait_items: [],
  weight_review_blocked: true,
  weight_review_block_reason: "성과 성숙 상태가 없어 추천 산식 검토를 막는다.",
  manual_weight_review_allowed: false,
  recommendation_scoring_mutated: false,
  benchmark_definition_mutated: false,
  portfolio_position_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_rebalance_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_PROFESSIONAL_SOURCE_GAP_PRIORITIZATION: ProfessionalSourceGapPrioritization = {
  status: "missing",
  as_of_date: "",
  gap_count: 0,
  high_priority_count: 0,
  source_blocker_count: 0,
  fund_not_applicable_count: 0,
  fund_source_gap_count: 0,
  coverage_gap_count: 0,
  guarded_source_blocked_recommendation_count: 0,
  attention_required: false,
  top_priority_score: 0,
  gaps: [],
  next_action: "전문 분석 원천 공백을 먼저 계산한다.",
  recommendation_scoring_mutated: false,
  automatic_weight_change_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};

export const DEFAULT_PROFILE_SCHEDULER: ProfileSchedulerStatus = {
  status: "not_configured",
  install_status: "not_installed",
  scheduler_type: "",
  timer_count: 0,
  active_timer_count: 0,
  generated_at: "",
  source: "not_configured",
  timers: [],
};

export const DEFAULT_PRODUCTION_API_SERVER: ProductionApiServer = {
  status: "missing_runtime_evidence",
  attention_required: true,
  service: "frontend-api-server",
  runtime_profile: "unknown",
  source_mode: "unknown",
  auth_mode: "unknown",
  read_auth_required: false,
  read_token_configured: false,
  allowed_origin_configured: false,
  database_configured: false,
  connection_boundary: "missing_executor",
  request_timeout_seconds: 30,
  read_only: true,
  missing_conditions: ["runtime_profile_production", "read_token_auth", "psycopg_pool_boundary"],
  order_boundary: "read_only_no_order",
  automatic_action_allowed: false,
  next_action: "읽기 서버 실행 환경, 조회 권한, 허용 출처, DB 설정, DB 연결 경계를 본다.",
};

export const DEFAULT_AUTH_RBAC: AuthRbac = {
  status: "missing_rbac_evidence",
  attention_required: true,
  mode: "disabled",
  auth_mode: "unknown",
  read_role: "viewer",
  read_allowed_roles: ["viewer", "analyst", "operator", "admin"],
  read_token_configured: false,
  role_valid: true,
  protected_paths: ["/__endpoints", "/api/*"],
  public_paths: ["/__live", "/__health", "/__ready"],
  allowed_methods: ["GET", "HEAD", "OPTIONS"],
  write_methods_allowed: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
  missing_conditions: ["production_api_ready", "bearer_read_token", "read_only_rbac_mode"],
  summary: "읽기 서버의 읽기 토큰, 조회 역할, 쓰기/주문 차단 경계 증거가 아직 부족하다.",
  next_action: "읽기 서버 준비, 읽기 토큰, 조회 역할, 쓰기 요청 차단, 증권사 주문 차단을 본다.",
};

export const DEFAULT_ALERT_DESTINATION: AlertDestination = {
  status: "missing_destination",
  attention_required: true,
  mode: "missing",
  destination_type: "unknown",
  external_destination: false,
  local_only: false,
  target_configured: false,
  status_artifact_configured: false,
  status_artifact_loaded: false,
  last_test_status: "missing",
  last_tested_at: "",
  test_recent: false,
  test_age_hours: null,
  max_test_age_hours: 168,
  missing_conditions: ["external_alert_destination", "alert_target_configured", "alert_test_passed"],
  summary: "예약 실행 중단과 데이터 오염을 받을 외부 알림 목적지가 설정되지 않았다.",
  next_action: "무료 webhook, email, Telegram, Slack, Discord 중 하나를 저장소 밖 환경 파일에 설정하고 테스트 기록을 남긴다.",
  order_boundary: "read_only_no_order",
  automatic_action_allowed: false,
};

export const DEFAULT_DATA_OPERATIONS_ARTIFACT_RUNNER: DataOperationsArtifactRunner = {
  status: "missing_pipeline_evidence",
  attention_required: true,
  job_count: 0,
  artifact_policy_count: 0,
  latest_run_count: 0,
  failed_or_missing_count: 0,
  degraded_count: 0,
  profile_scheduler_installed: false,
  timer_count: 0,
  active_timer_count: 0,
  manual_smoke_status: "missing",
  local_worker_status: "missing",
  latest_artifact_root: "",
  order_boundary: "read_only_no_order",
  automatic_action_allowed: false,
  next_action: "실행 증거 저장기를 통해 성공한 데이터 작업 기록을 먼저 생성한다.",
};

export const DEFAULT_ACTIVE_RECOMMENDATION_PRICE_FRESHNESS: ActiveRecommendationPriceFreshness = {
  status: "missing",
  attention_required: true,
  active_symbol_count: 0,
  fresh_symbol_count: 0,
  stale_symbol_count: 0,
  missing_symbol_count: 0,
  stale_recommendation_count: 0,
  missing_recommendation_count: 0,
  global_latest_trade_date: "",
  stale_after_days: 7,
  max_days_behind_latest: 0,
  stale_symbols: [],
  next_action: "active 추천 종목 가격 최신성 감사를 먼저 생성한다.",
  recommendation_scoring_mutated: false,
  automatic_order_allowed: false,
  broker_submit_allowed: false,
  order_boundary: "read_only_no_order",
};
