import { type MutableRecord, withDefault } from "./frontend-normalizer-utils";

function defaultTossInvestMarketData() {
  return {
    sync: {
      status: "not_configured",
      latest_status: "missing",
      latest_run_id: null,
      finished_at: "",
      provider: "tossinvest",
      sync_mode: "not_available",
      market_code: "",
      requested_symbol_count: 0,
      candle_symbol_count: 0,
      candle_bar_count: 0,
      stock_warning_symbol_count: 0,
      market_microdata_symbol_count: 0,
      unresolved_symbol_count: 0,
      collection_cadence: {},
      credentials_configured: false,
      missing_env_vars: [],
      operator_action: "Toss 시장 데이터 수집 설정과 최신 실행 상태를 확인한다.",
      attention_required: true,
      broker_submit_allowed: false,
      submitted_to_broker: false,
      order_boundary: "read_only_no_order",
      secret_free: true,
    },
    provider_comparison: {
      status: "missing",
      latest_status: "missing",
      latest_run_id: null,
      finished_at: "",
      symbol_count: 0,
      comparison_date: "",
      lookback_days: 5,
      max_diff_bps: "50",
      canonical_promotion_blocked: true,
      attention_required: true,
      broker_submit_allowed: false,
      submitted_to_broker: false,
      secret_free: true,
    },
  };
}

function defaultWeightReviewReadinessSemanticsV2() {
  return {
    status: "missing",
    eval_run_id: "eval-run-unknown",
    created_at: "",
    mode: "shadow_read_only",
    authoritative: false,
    decision: "missing_shadow_evidence",
    evidence_sufficient_for_pilot_request: false,
    manual_review_eligible: false,
    pilot_scope_defined: false,
    explicit_user_approval_present: false,
    read_only_pilot_start_allowed: false,
    proposal_generation_allowed: false,
    weight_mutation_allowed: false,
    automatic_weight_change_allowed: false,
    portfolio_position_mutation_allowed: false,
    automatic_order_allowed: false,
    broker_submit_allowed: false,
    order_boundary: "read_only_no_order",
    source_snapshot: {},
    sample_identity: {
      status: "missing",
      identity_attested: false,
      quality_observation_unit: "",
      quality_recommendation_count: null,
      quality_outcome_count: null,
      horizon_observation_unit: "",
      recommendation_horizon_observation_count: null,
      horizon_outcome_observation_count: null,
      portfolio_feedback_observation_unit: "",
      portfolio_feedback_run_count: null,
      portfolio_feedback_decision_count: null,
      portfolio_feedback_mature_decision_count: null,
      quality_component_metrics_sha256: "",
      outcome_horizon_coverage_sha256: "",
      portfolio_feedback_evidence_sha256: "",
      stable_row_level_sample_identity_attested: false,
      feedback_deduplication_attested: false,
      versioned_component_snapshot_integrity_attested: false,
      freshness_policy_attested: false,
      temporal_freshness_status: "policy_not_defined",
      source_age_days: {
        readiness: null,
        quality: null,
        outcome: null,
        portfolio_feedback: null,
      },
      limitations: [],
    },
    horizon_evidence: {
      horizon_days: [],
      observation_unit: "recommendation_x_horizon",
      filters: {},
      rows: [],
      aggregate_summary: {
        recommendation_count: null,
        recommendation_horizon_count: null,
        outcome_count: null,
        ready_for_backfill_count: null,
        not_due_count: null,
        missing_entry_price_count: null,
        missing_exit_price_count: null,
        benchmark_warning_count: null,
        outcome_coverage_rate: null,
      },
      aggregate_consistent: false,
      approved_horizon_policy_attested: false,
      policy_limitation: "",
    },
    evidence_readiness: {
      status: "missing",
      source_coherent: false,
      legacy_readiness_ready: false,
      quality_threshold_ready: false,
      outcome_calibration_ready: false,
      threshold_evidence_ready: false,
      portfolio_feedback_ready: false,
      legacy_integrity_attested: false,
      blockers: [{ code: "missing_shadow_evidence", message: "" }],
    },
    manual_review_eligibility: {
      eligible: false,
      scope: "read_only_human_evidence_review",
      requires_source_coherence: true,
      requires_legacy_readiness: true,
      requires_portfolio_feedback: true,
      requires_attested_sample_integrity: true,
      requires_approved_horizon_policy: true,
      reason: "Shadow evidence does not establish read-only review eligibility.",
    },
    explicit_user_authorization: {
      status: "explicit_approval_required",
      required: true,
      present: false,
      scope_defined: false,
      approval_reference: null,
      reason: "This shadow audit cannot record or infer scoped user approval.",
    },
    pilot: {
      status: "not_started_not_authorized",
      pilot_scope_defined: false,
      read_only_pilot_start_allowed: false,
      proposal_generation_allowed: false,
      started: false,
      reason: "No pilot is authorized or started by this audit.",
    },
    mutation_boundary: {
      status: "blocked_read_only_shadow",
      recommendation_scoring_mutated: false,
      weight_mutation_allowed: false,
      automatic_weight_change_allowed: false,
      portfolio_position_mutation_allowed: false,
      automatic_order_allowed: false,
      broker_submit_allowed: false,
      order_boundary: "read_only_no_order",
    },
    legacy_comparison: {
      readiness_eval_run_id: "eval-run-unknown",
      readiness_decision: "missing",
      legacy_manual_weight_review_allowed: false,
      quality_eval_run_id: "eval-run-unknown",
      quality_status: "unknown",
      outcome_eval_run_id: "eval-run-unknown",
      outcome_status: "missing",
      portfolio_feedback_eval_run_id: "eval-run-unknown",
      portfolio_feedback_status: "missing",
      interpretation: "",
    },
  };
}

export function normalizeDataHealthPayload(data: MutableRecord) {
  withDefault(data, "tossinvest_market_data", defaultTossInvestMarketData());
  withDefault(
    data,
    "recommendation_weight_review_readiness_semantics_v2",
    defaultWeightReviewReadinessSemanticsV2(),
  );
}
