const KOREAN_LABELS: Record<string, string> = {
  ANNUAL_REPORTING: "연간 공시",
  ALL: "전체",
  CASH: "현금",
  EVIDENCE: "증거",
  EXCLUDE: "제외",
  REC: "추천",
  Theme: "테마",
  Thesis: "투자 논리",
  DOC: "문서",
  UNKNOWN: "종목 미분류",
  UNCLASSIFIED: "테마 미분류",
  MARKET_NEWS_FLOW: "시장 뉴스 흐름",
  US_MARKET_BREADTH: "미국 시장 참여도",
  QUANTUM_COMPUTING_POLICY: "양자컴퓨팅·정책 수혜",
  AI_SEMICONDUCTOR_CYCLE: "AI 반도체 사이클",
  AI_LABOR_PRODUCTIVITY: "AI 도입·노동 영향",
  MACRO_RATES_FED: "금리·연준",
  MACRO_INFLATION: "물가·인플레이션",
  MACRO_LIQUIDITY: "유동성·신용",
  MACRO_GROWTH: "성장·경기",
  TECH_DOMAIN: "기술 도메인",
  "Technology Domain": "기술 도메인",
  ENERGY_DOMAIN: "에너지 도메인",
  ENERGY_GEOPOLITICS: "에너지·지정학",
  BROAD_US_EQUITY: "미국 광범위 주식",
  "BROAD US EQUITY": "미국 광범위 주식",
  "Broad US Equity": "미국 광범위 주식",
  TECHNOLOGY: "기술 섹터",
  ENERGY: "에너지 섹터",
  FINANCIALS: "금융 섹터",
  FIXED_INCOME: "채권",
  "FIXED INCOME": "채권",
  CONSUMER_DISCRETIONARY: "임의소비재",
  "CONSUMER DISCRETIONARY": "임의소비재",
  "Macro Liquidity Regime": "유동성·신용",

  Long: "장기",
  "Long Term Paper": "장기 가상 포트폴리오",
  annual_reporting: "연간 공시",
  market_news_flow: "시장 뉴스 흐름",
  us_market_breadth: "미국 시장 참여도",
  quantum_computing_policy: "양자컴퓨팅·정책 수혜",
  ai_semiconductor_cycle: "AI 반도체 사이클",
  ai_labor_productivity: "AI 도입·노동 영향",
  macro_rates_fed: "금리·연준",
  macro_inflation: "물가·인플레이션",
  macro_liquidity: "유동성·신용",
  macro_growth: "성장·경기",
  tech_domain: "기술 도메인",
  energy_domain: "에너지 도메인",
  energy_geopolitics: "에너지·지정학",
  broad_us_equity: "미국 광범위 주식",
  technology: "기술 섹터",
  energy: "에너지 섹터",
  financials: "금융 섹터",
  fixed_income: "채권",
  consumer_discretionary: "임의소비재",
  active: "활성",
  alert_destination: "알림 목적지",
  discord: "Discord",
  email: "이메일",
  external_destination_verified: "외부 알림 검증됨",
  journal: "시스템 로그",
  local_file: "로컬 파일",
  local_only_not_external: "로컬 기록만 있음",
  missing_destination: "알림 목적지 없음",
  missing_target: "알림 대상 미설정",
  missing_test: "알림 테스트 미실행",
  ntfy: "ntfy",
  slack: "Slack",
  stale_test: "알림 테스트 오래됨",
  telegram: "Telegram",
  unsupported_mode: "지원하지 않는 알림 방식",
  webhook: "Webhook",
  ai: "AI",
  llm: "AI",
  codex_oauth: "AI 배치 분석",
  fixture: "기준 세트",
  news_ai_extraction_quality: "뉴스 근거 추출 품질",
  "news-ai-eval-v1": "뉴스 근거 평가 v1",
  "news-ai-eval-fixture-v1": "뉴스 근거 기준 세트 v1",
  "news-ai-eval-intraday": "뉴스 근거 회귀평가",
  news_ai_eval_quality_attention: "뉴스 근거 회귀평가 확인 필요",
  failed_regression: "회귀평가 미통과",
  macro_fed_rates_no_direct_ticker: "금리 뉴스 종목 오부착 차단",
  direct_nvda_ai_chip_news: "NVDA AI 반도체 뉴스 직접 영향",
  quantum_policy_not_energy: "양자 정책 뉴스 에너지 오분류 차단",
  energy_shock_direct_energy: "에너지 충격 직접 영향",
  energy_shock_exxon_direct: "에너지 충격 XOM 직접 영향",
  ai_semiconductor_direct_stock: "AI 반도체 직접 종목 영향",
  low_signal_blocked: "저신호 항목 차단",
  low_signal_should_block: "저신호 뉴스 차단",
  macro_only: "거시 뉴스",
  quantum_policy: "양자 정책",
  energy_shock: "에너지 충격",
  direct_stock: "직접 종목 뉴스",
  low_signal: "저신호 뉴스",
  "codex-cli-default": "Codex 기본 모델",
  "codex oauth": "AI 배치 분석",
  alpha_vantage: "Alpha Vantage",
  all: "전체",
  "attention required": "주의 필요",
  attention_required: "주의 필요",
  auth_rbac: "인증/RBAC",
  admin: "관리자",
  analyst: "분석가",
  "frontend:read": "화면 읽기",
  missing_rbac_evidence: "인증/RBAC 증거 부족",
  operator: "운영자",
  "read-only-token": "읽기 전용 토큰",
  read_only_rbac_ready: "읽기 전용 RBAC 확인됨",
  viewer: "조회자",
  ai_artifact_linkage: "투자 근거 연결",
  decision_linkage: "추천 연결",
  korean_translation: "한국어 번역",
  postgres_sql_graph_context: "Postgres 내부 근거 검색",
  source_grounding: "원천 근거",
  write_order_boundary: "쓰기/주문 차단",
  ai_structure: "투자 영향",
  available: "확인됨",
  macro_or_theme_only: "상위 흐름",
  needs_neighborhood_lookup: "종목 맥락 확인",
  source: "원천",
  "event_and_ai_evidence": "뉴스·투자 근거",
  "fund_instrument_analysis": "ETF·펀드 근거",
  "market.financial_metric_normalized": "정규화 재무 지표",
  "market.valuation_snapshot": "밸류에이션 원천",
  "research.equity_research_artifact": "AI 기업 리서치",
  "research.industry_competitive_position": "피어·산업 위치",
  "signal.investment_thesis": "투자 논리",
  "signal.recommendation": "추천 신호",
  translation: "번역",
  validator: "품질 기준",
  twelve_data: "Twelve Data",
  fred: "FRED",
  cboe_csv: "CBOE",
  accumulate: "분할 매수",
  accumulate_candidate: "분할 매수 판단 항목",
  "accumulate candidate": "분할 매수 판단 항목",
  avoid: "회피",
  blocked: "차단",
  broker_boundary: "증권사 연결 상태",
  buy: "매수",
  completed: "완료",
  constructive: "건설적",
  configured: "설정됨",
  configure_scheduler_activation_gate_report: "자동 실행 승인 조건 설정 필요",
  covered: "커버됨",
  correcting: "조정 중",
  expanding: "확산",
  cycle: "사이클",
  daily: "일간",
  weekly: "주간",
  monthly: "월간",
  intraday: "장중",
  failed: "중단",
  degraded: "상태 저하",
  succeeded_with_fallback: "예비 경로로 완료",
  forming: "형성 중",
  cooling: "냉각",
  confirming: "확인 국면",
  "cycle confirming": "사이클 확인 국면",
  healthy: "정상",
  high: "높음",
  human_review_required: "자동 판단 보류",
  ai_review_required: "품질 확인 필요",
  ai_review_passed: "품질 기준 통과",
  ai_review_pending: "품질 확인 대기",
  deterministic_ai_review_required: "품질 확인 필요",
  source_document_ai_review_required: "원천 문서 품질 확인 필요",
  low_signal_suppressed: "저신호 보류",
  quality_gate: "검증 조건",
  human_risk_review: "AI 리스크 검토",
  in_progress: "진행 중",
  low: "낮음",
  long_term: "장기",
  long_term_core: "장기 핵심 전략",
  "bootstrap-v1": "초기화 v1",
  "fixture-v1": "검증용 v1",
  medium: "중간",
  measured: "측정됨",
  missing: "누락",
  missing_configuration: "설정 누락",
  missing_outcome: "성과 측정 누락",
  missing_thesis: "투자 논리 누락",
  missing_weight: "비중 누락",
  monitor: "관찰 유지",
  monitor_or_accumulate: "관찰 또는 분할 매수",
  no_recommendation: "추천 없음",
  unmeasured: "아직 성과 측정 전",
  needs_outcome_review: "성과 검토 필요",
  needs_evidence_review: "근거 보강 필요",
  needs_thesis_review: "투자 논리 검토 필요",
  needs_weight_review: "비중 검토 필요",
  neutral: "중립",
  risk_on: "위험자산 선호",
  risk_off: "위험 회피",
  real_rate_pressure: "실질금리 부담",
  dollar_liquidity_tightening: "달러 유동성 긴축",
  commodity_reflation: "원자재 재가속",
  safe_haven_bid: "안전자산 선호",
  credit_stress: "신용 스트레스",
  volatility_shock: "변동성 충격",
  growth_slowdown: "성장 둔화",
  no_quota_available: "무료 한도 소진",
  none: "없음",
  normal: "일반",
  not_configured: "미설정",
  not_due: "아직 실행 대상 아님",
  not_installed: "미설치",
  not_requested: "아직 요청되지 않음",
  "not requested": "아직 요청되지 않음",
  not_applicable: "해당 없음",
  "not applicable": "해당 없음",
  not_available: "아직 없음",
  no_op_not_available: "아직 실행 정보 없음",
  "waiting for outcome window": "성과 관찰 기간 대기",
  "managed wait until outcome window": "성과 관찰 기간까지 대기",
  "decision history has not reached the minimum outcome observation window.": "저장된 판단이 아직 최소 성과 관찰 기간을 채우지 못했다.",
  not_triggered: "미발동",
  ignored: "무시됨",
  open: "열림",
  openai: "AI 배치 분석",
  OPENAI: "AI 배치 분석",
  outperform: "벤치마크 상회",
  "news rss korean translation": "뉴스 한국어 번역",
  "news rss enrichment intraday": "뉴스 1차 분류",
  "news ai evidence intraday": "뉴스 근거 분석",
  "news ai extraction quality": "뉴스 근거 추출 품질",
  "sec companyfacts upsert": "SEC 기업 재무 원천 적재",
  "financial period source linkage": "재무 기간 원천 연결",
  "professional coverage expansion": "전문 분석 커버리지 보강",
  "financial metric normalization": "재무 지표 정규화",
  "peer relative analysis": "피어 상대 분석",
  "financial forecast inputs": "재무 전망 입력",
  "reported segment footnote parser": "사업부 주석 파서",
  "segment footnote evidence": "사업부 주석 근거",
  "sum of parts valuation": "SOTP 밸류에이션",
  "valuation snapshot": "밸류에이션 스냅샷",
  "industry competitive positioning": "산업 경쟁력 분석",
  "market symbol seed": "시장 종목군 초기화",
  "macro data upsert": "거시 데이터 적재",
  "sec filing ingest": "SEC 공시 적재",
  passed: "통과",
  pending: "대기",
  paper_buy_to_target: "가상 목표 비중 매수 항목",
  paper_hold: "가상 보유 유지",
  paper_increase_to_target: "가상 목표 비중 증액 항목",
  paper_reduce_to_target: "가상 목표 비중 감액 항목",
  paper_review_no_recommendation: "추천 없는 보유 검토",
  paper_sell_to_zero: "가상 전량 매도 항목",
  paper_ready: "가상 거래 준비 완료",
  ready_for_paper_audit: "가상 감사 준비",
  ready_for_human_review: "AI 검증 통과",
  paper_validation_required: "가상 매매 검증 필요",
  pass: "통과",
  warning: "주의",
  paper: "가상 매매",
  live: "실거래",
  paper_trade: "가상 매매 권한",
  live_trade: "실거래 권한",
  read_only: "읽기 전용",
  revoked: "철회",
  inactive: "비활성",
  disabled: "비활성",
  enabled: "활성",
  global: "전체",
  fallback: "대체 처리",
  default_fallback: "기본 비중 정책",
  read_only_fallback: "읽기 전용 대기",
  lifecycle_not_available: "투자 논리 생애주기 미연결",
  global_default_long_term_guardrail: "장기 기본 비중 안전장치",
  account_permission: "계좌 권한",
  order_limit_policy: "주문 한도",
  order_boundary: "주문 차단",
  kill_switch: "킬 스위치",
  paper_validation: "가상 매매 검증",
  paper_validation_and_order_boundary: "가상 매매·실거래 상태",
  portfolio_risk_budget_guardrail: "포트폴리오 위험 예산",
  portfolio_risk_budget_guardrail_blocker: "위험 예산 차단 사유",
  blocked_by_risk_budget_review: "위험 예산 검토 필요",
  blocked_by_professional_source_data: "전문 재무 원천 차단",
  source_data_blocked: "전문 재무 원천 차단",
  missing_portfolio_risk_budget_guardrail: "위험 예산 검증 없음",
  over_single_position_limit: "단일 종목 한도 초과",
  sector_over_limit: "섹터 집중도 한도 초과",
  theme_over_limit: "테마 집중도 한도 초과",
  unclassified_exposure_over_limit: "미분류 노출 한도 초과",
  insufficient_benchmark_composition: "벤치마크 구성비 부족",
  benchmark_composition_partial: "부분 벤치마크 구성비",
  calculated_partial_composition: "부분 구성비로 계산",
  partial_composition: "부분 구성비",
  stale_composition: "오래된 구성비",
  missing_benchmark_composition: "벤치마크 구성비 없음",
  missing_benchmark_drift: "벤치마크 괴리 미계산",
  missing_guardrail: "위험 예산 평가 없음",
  drift_outlier_review: "괴리 검토 필요",
  review_required: "검토 필요",
  recommendation_weights_unchanged: "추천 가중치 변경 없음",
  watch_only: "관찰만 필요",
  within_policy: "정책 범위 내",
  no_positions: "보유 종목 없음",
  not_reviewed: "검토 전",
  in_line: "평균 수준",
  within_review_band: "검토 범위 내",
  read_only_no_order: "읽기 전용·주문 금지",
  trim_active_overweight_review: "과대 active 비중 축소 검토",
  review_active_underweight_gap: "과소 active 비중 사유 검토",
  overweight: "과대 보유",
  underweight: "과소 보유",
  reduce_review: "축소 검토",
  add_blocked_until_evidence: "증거 보강 전 증액 금지",
  watch_small_position: "작은 비중 관찰",
  hold_review: "유지 검토",
  thesis_missing: "투자 논리 누락",
  thesis_connected: "투자 논리 연결",
  active_overweight_review: "벤치마크 대비 과대 보유",
  valuation_unavailable: "밸류에이션 없음",
  negative_margin_of_safety: "안전마진 부족",
  positive_margin_of_safety: "안전마진 있음",
  fundamental_component_unavailable: "재무 품질 점수 없음",
  fundamental_quality_supportive: "재무 품질 양호",
  equity_research_unavailable: "기업 리서치 없음",
  equity_research_available: "기업 리서치 있음",
  complete: "완료",
  partial: "부분 완료",
  composition_available: "구성비 존재",
  composition_coverage: "구성비 커버리지",
  source_freshness: "구성 기준일",
  drift_outliers: "괴리 종목",
  audit_log: "검토 기록",
  pending_manual_approval: "수동 승인 대기",
  add: "편입",
  buy_candidate: "매수 판단 항목",
  keep: "유지",
  reduce: "비중 축소",
  increase_to_target: "목표 비중까지 증액 검토",
  trim_to_target: "과대 비중 축소 검토",
  "trim single name exposure": "단일 종목 비중 축소 검토",
  "review sector theme concentration": "섹터·테마 집중도 검토",
  allocation_review: "비중 검토",
  allocation_policy_review: "비중 정책 검토",
  structurally_broken: "구조 훼손",
  account_daily_notional_limit_exceeded: "계좌 일일 한도 초과",
  account_order_notional_limit_exceeded: "계좌 단일 주문 한도 초과",
  account_permission_not_active: "계좌 권한 비활성",
  account_permission_scope_insufficient: "계좌 권한 범위 부족",
  broker_boundary_not_enabled: "증권사 연결 상태 비활성",
  broker_preview_not_supported: "주문 미리보기 미지원",
  human_approval_required: "거래 안전 승인 필요",
  kill_switch_engaged: "킬 스위치 작동 중",
  order_limit_policy_not_active: "주문 한도 정책 비활성",
  position_recommendation_conflict: "보유와 추천 충돌",
  single_order_notional_limit_exceeded: "단일 주문 금액 한도 초과",
  single_order_weight_delta_limit_exceeded: "단일 주문 비중 변화 한도 초과",
  symbol_not_allowed_for_account: "계좌 허용 종목 아님",
  production_api_server: "운영 API 서버",
  risk_review: "리스크 검토",
  resolved: "해결",
  news_rss: "뉴스 RSS",
  NEWS_RSS: "뉴스 RSS",
  news_rss_item: "뉴스 RSS 항목",
  NEWS_RSS_ITEM: "뉴스 RSS 항목",
  "news rss item": "뉴스 RSS 항목",
  browser_download_disabled_until_auth_rbac: "접근 권한 준비 전까지 원문 열람 제한",
  news_cluster_summary: "뉴스 묶음 근거",
  news_cluster_summary_v1: "뉴스 묶음 요약 v1",
  news_event_candidate: "뉴스 투자 근거",
  news_event_candidate_rejected: "차단된 뉴스 투자 근거",
  news_event_candidate_suppressed: "저신호 뉴스 투자 근거",
  validator_blocked: "검증 차단",
  local_rules: "무료 로컬 규칙",
  local_deterministic: "무료 로컬 규칙",
  free_local_rules: "무료 로컬 규칙",
  postgres_sql: "DB 조회",
  postgres_canonical_tables: "DB 표준 저장소",
  read_only_evidence_neighborhood: "읽기 전용 증거 관계망",
  not_indexed: "원문 저장됨",
  indexed: "원문 확인 가능",
  contains: "포함",
  belongs_to: "소속",
  parent_child: "상하위",
  analysis_method: "근거 성격",
  event_count: "이벤트 수",
  linked_symbols: "연결 종목",
  sec_filing: "SEC 공시",
  sec_10k_filing: "SEC 10-K 공시",
  "sec 10k filing": "SEC 10-K 공시",
  sec_annual_report_filed: "SEC 연간보고서 제출",
  "sec annual report filed": "SEC 연간보고서 제출",
  security_selection: "종목 선택",
  same_source_document: "같은 원천 문서",
  same_symbol: "같은 종목",
  same_theme: "같은 테마",
  ai_or_event_evidence: "뉴스·AI 근거",
  event_or_ai_evidence: "원천 이벤트/AI 근거",
  linked_thesis: "투자 논리 연결",
  market_feature: "가격 지표",
  market_feature_provenance: "가격/순위 입력 근거",
  outcome_measurement: "성과 측정",
  return_1d: "1일 수익률",
  return_since_first_observation: "관측 시작 이후 수익률",
  score_components: "점수 구성요소",
  strategy_universe_rank: "전략 종목군 순위",
  source_events: "원천 이벤트",
  performance_evidence: "성과 근거",
  invalidation_conditions: "무효화 조건",
  latest_human_review: "최근 AI 자동 검토",
  latest_ai_review: "최근 AI 자동 검토",
  scheduler_activation_approval_gate_report: "자동 실행 승인 기록",
  scheduler_activation_manual_approval: "스케줄러 수동 승인",
  source_document_event: "원천 문서 이벤트",
  source_document_review_required: "원천 문서 AI 검증 필요",
  "source document review required": "원천 문서 AI 검증 필요",
  succeeded: "성공",
  supportive: "우호적",
  theme_exposure: "테마 노출",
  thesis_or_position_link_review: "투자 논리/포지션 연결 검토",
  thesis_remediation: "투자 논리 보완",
  underperform: "벤치마크 하회",
  invalid_report: "잘못된 report",
  ok: "정상",
  observed: "관측됨",
  market: "시장",
  macro: "거시",
  news: "뉴스",
  performance: "성과",
  portfolio: "포트폴리오",
  sec: "SEC",
  signal: "신호",
  market_daily_price_bar: "일간 가격 바",
  "market.daily_price_bar": "가격 캔들",
  macro_weekly: "주간 거시 데이터",
  market_price_upsert: "시장 가격 적재",
  market_price_daily: "일간 시장 가격 적재",
  "market-price-daily": "일간 시장 가격 적재",
  news_rss_upsert: "뉴스 RSS 적재",
  news_rss_daily: "일간 뉴스 RSS 적재",
  "news-rss-daily": "일간 뉴스 RSS 적재",
  news_rss_event_enrichment: "뉴스 이벤트 구조화",
  "news-rss-enrichment-intraday": "뉴스 이벤트 구조화",
  event_intelligence_weekly: "뉴스 근거 분석",
  "event-intelligence-weekly": "뉴스 근거 분석",
  "market-universe-weekly": "주간 종목군",
  "sec-filings-weekly": "주간 SEC 공시",
  "news-intraday": "뉴스/AI 장중 반복",
  "market-daily": "일간 주식 캔들",
  "decision-daily": "일간 신호/추천/보유 상태 판단",
  "macro-weekly": "주간 거시",
  "performance-monthly": "월간 성과 측정",
  "cycle-recommendation-weekly": "사이클/추천 생성",
  preview_not_executed: "미리보기만 생성됨",
  missing_report: "요약 report 없음",
  manual_local_ingest_smoke_report: "수동 수집 요약",
  local_ingest_worker_report: "반복 실행 요약",
  cycle_ai_quality_audit: "사이클·AI 품질 감사",
  cycle_ai_quality_audit_report: "사이클·AI 품질 감사 요약",
  cycle_ai_quality_audit_attention: "사이클·AI 품질 감사 주의",
  managed_warning: "관리 중 경고",
  recommendation_outcome_calibration_attention: "추천 성과검증 주의",
  recommendation_outcome_calibration_sample_expansion: "추천 성과검증 표본 확장",
  recommendation_outcome_maturity_attention: "성과 측정창 주의",
  recommendation_outcome_due_action_router_attention: "성과 실행 라우터 주의",
  recommendation_outcome_due_action_router: "추천 성과 실행 라우터",
  "recommendation-outcome-due-action-router-daily": "추천 성과 실행 라우터",
  execute_outcome_calibration_ready: "성과 calibration 실행 대기",
  outcome_calibration_executed: "성과 calibration 실행됨",
  no_op_wait_until_next_due_date: "다음 측정일까지 대기",
  no_op_current_window_complete: "현재 측정창 처리 완료",
  no_op_no_active_recommendation_horizons: "활성 추천 없음",
  no_op_no_outcome_sample_available: "성과 표본 없음",
  due_outcomes_ready: "성과 산출 가능",
  overdue_outcomes_ready: "성과 산출 지연",
  blocked_by_price_gaps: "가격 이력 보강 필요",
  no_active_recommendation_horizons: "활성 추천 없음",
  complete_current_window: "현재 창 측정 완료",
  run_outcome_calibration_now: "성과 calibration 즉시 실행",
  repair_price_history_then_calibrate: "가격 보강 후 calibration",
  wait_until_next_due_date: "다음 측정일까지 대기",
  no_due_work_keep_monitoring: "처리할 성과창 없음",
  inspect_outcome_maturity_state: "성과창 상태 확인",
  collect_more_outcomes_keep_weights: "성과 표본 축적 중",
  backfill_candidates_remain: "성과 산출 대상 남음",
  price_history_gaps_remain: "가격 이력 보강 필요",
  ready_for_manual_weight_review: "성과 표본 충족",
  blocked_by_outcome_calibration_no_due_outcome_window: "성과 측정일 대기",
  blocked_by_outcome_calibration_backfill_candidates_remain: "성과 산출 먼저 필요",
  blocked_by_outcome_calibration_price_history_gaps_remain: "가격 이력 보강 필요",
  blocked_by_outcome_calibration_no_outcome_sample_available: "성과 표본 없음",
  blocked_by_outcome_calibration_missing: "성과 calibration 없음",
  blocked_by_outcome_calibration_not_ready: "성과 calibration 미통과",
  missing_recommendation_weight_review_readiness: "추천 산식 검토 증거 없음",
  no_outcome_sample_available: "성과 표본 없음",
  no_due_outcome_window: "성과 측정일 대기",
  missing_recommendation_outcome_calibration: "추천 성과검증 없음",
  insufficient_sample: "표본 부족",
  sufficient_sample: "표본 충분",
  ready_for_backfill: "성과 산출 가능",
  missing_entry_price: "진입 가격 없음",
  missing_exit_price: "종료 가격 없음",
  outcome_recorded: "성과 기록됨",
  "run cycle-ai-quality-audit-run --execute --output outside the repository":
    "저장소 밖 경로에 사이클·AI 품질 감사 결과를 생성한다",
  "run news-intraday and decision-daily before trusting recommendations":
    "추천을 신뢰하기 전에 뉴스/AI와 일간 신호 작업을 다시 실행한다",
  "inspect quantum news theme grounding and remove energy mislinks":
    "양자 뉴스가 에너지 테마로 잘못 연결된 항목을 확인해 제거한다",
  "inspect cross-theme news mismatches before using cycle evidence":
    "사이클 근거로 쓰기 전에 뉴스 내용과 맞지 않는 테마 연결을 확인한다",
  "review direct ticker impacts without source-text grounding":
    "원문 근거 없이 직접 종목에 연결된 뉴스를 확인한다",
  "keep macro-only news at macro/theme level until propagation adds instrument impact":
    "거시 뉴스는 전파 엔진이 종목 영향을 만들 때까지 상위 흐름으로 유지한다",
  "deduplicate repeated RSS titles before cluster evidence":
    "뉴스 묶음 근거를 만들기 전에 반복 수집된 같은 제목을 정리한다",
  "merge duplicate news flow evidence before cycle review":
    "사이클 검토 전에 같은 뉴스가 여러 흐름으로 부풀려진 항목을 합친다",
  "review weak cycle propagation evidence before recommendation input":
    "추천 입력 전에 신뢰도나 경로 가중치가 낮은 전파 근거를 확인한다",
  "run Korean translation batch before user-facing review":
    "사용자 화면 검토 전에 한국어 번역 배치를 실행한다",
  "continue scheduled news, propagation, cycle snapshot, and paper validation runs":
    "뉴스, 전파, 사이클 스냅샷, 가상 매매 검증 자동 실행을 계속 유지한다",
  "regenerate cycle AI quality audit report": "사이클·AI 품질 감사 요약 파일을 다시 생성한다",
  "run manual-local-ingest-smoke --output outside the repository":
    "저장소 밖 경로에 수동 수집 결과를 다시 생성한다",
  "run local-ingest-worker-run --output outside the repository":
    "저장소 밖 경로에 반복 실행 결과를 다시 생성한다",
  "open /data-health and verify the latest local ingest worker cycle": "데이터 수집 화면에서 최신 반복 실행 결과를 확인한다",
  "open /data-health and verify latest pipeline state": "데이터 수집 화면에서 최신 작업 상태를 확인한다",
  market_universe_bootstrap: "시장 종목군 초기화",
  macro_upsert: "거시 데이터 적재",
  sec_filings_upsert: "SEC 공시 적재",
  event_intelligence_llm_extract: "뉴스·AI 근거 분석",
  news_rss_ai_extract: "뉴스 근거 추출",
  fixture_structured_news: "테스트용 구조화 뉴스",
  ai_structured_news: "투자 근거 뉴스",
  event_summary: "뉴스 요약",
  recommendation_relevance: "추천 검토 관련성",
  uncertainty_notes: "불확실성",
  theme_impact: "테마 영향",
  instrument_impact: "종목 영향",
  cycle_state_snapshot: "사이클 상태 스냅샷",
  portfolio_position_snapshot_upsert: "포트폴리오 포지션 적재",
  portfolio_position_daily: "일간 포트폴리오 포지션",
  portfolio_attribution_bootstrap: "포트폴리오 성과 귀속 초기화",
  performance_outcome_schedule_bootstrap: "성과 측정 일정 초기화",
  portfolio_remediation_daily: "일간 포트폴리오 검토 큐",
  "portfolio-remediation-daily": "일간 포트폴리오 검토 큐",
  portfolio_remediation_daily_automation: "포트폴리오 검토 큐 생성",
  performance_outcome_monthly: "월간 성과 측정",
  operations: "운영",
  "operating-data-profile-scheduler": "운영 데이터 자동 스케줄러",
  mixed: "혼합 주기",
  success: "성공",
  stale: "지연",
  installed: "설치됨",
  systemd: "서버 반복 실행기",
  installed_on_ec2_systemd: "EC2 반복 실행기 설치 완료",
  day_missing: "오늘 예산 기록 없음",
  "portfolio.position snapshot": "포트폴리오 포지션 스냅샷",
  "template rendered placeholder pending": "화면 구성 완료, 실제 데이터 연결 대기",
  "explicit skip dates": "명시 휴장일 사용",
  "data-operations-live-scheduler-activation-request": "스케줄러 활성화 요청 단계",
  blocked_pending_manual_approval: "수동 승인 대기",
  approved_for_manual_activation: "수동 활성화 승인됨",
  data_operations_live_scheduler_activation_request: "스케줄러 활성화 요청 단계",
  regenerate_scheduler_activation_gate_report: "자동 실행 승인 조건 재생성 필요",

  alpha_turns_negative_at_next_measurement: "다음 측정에서 알파가 음수로 전환",
  cash_timing: "현금 타이밍",
  coverage_ready: "커버리지 준비",
  cycle_state: "사이클 상태",
  cycle_state_breaks_to_negative: "사이클 상태가 부정적으로 전환",
  entity_and_theme_anchor: "기업/테마 기준점",
  event_intensity: "이벤트 강도",
  event_quality: "이벤트 신뢰도",
  event_quality_signal: "이벤트 신뢰도 신호",
  event_title: "이벤트 제목",
  fundamental_quality: "펀더멘털 신뢰도",
  methodology_boundary: "방법론 경계",
  outcome_run: "성과 측정 실행",
  performance_outcome: "성과 측정",
  position_weighted_alpha_v1: "포지션 비중 가중 알파 v1",
  price_momentum: "가격 모멘텀",
  "local provider budget ledger": "로컬 가격 API 예산 기록",
  local_provider_budget_ledger: "로컬 가격 API 예산 기록",
  repo_outside_budget_ledger: "저장소 밖 예산 기록",
  theme_mapping: "테마 매핑",
  unavailable: "미제공",
  unknown: "알 수 없음",
  watch: "관찰",

  "AAPL recommendation and thesis outcome are measured through 2024-12-02.":
    "AAPL 추천과 투자 논리 성과가 2024-12-02까지 측정되었습니다.",
  "AAPL remains covered by the annual reporting quality theme with constructive cycle evidence and positive benchmark-relative outcome.":
    "AAPL은 연간 공시 품질 테마, 건설적인 사이클 증거, 벤치마크 대비 양호한 성과로 계속 커버됩니다.",
  "AAPL is an active avoid recommendation linked to Annual Reporting. Cycle state is forming; recommendation score is 0.2579.":
    "AAPL은 연간 공시 테마에 연결된 활성 회피 추천입니다. 사이클 상태는 형성 중이고 추천 점수는 25.79%입니다.",
  "AAPL avoid thesis via Annual Reporting": "연간 공시 테마를 근거로 한 AAPL 회피 투자 논리",
  "AAPL thesis outcome pass": "AAPL 투자 논리 성과 통과",
  "Keep active recommendation status, selected universe membership, and direct theme/cycle evidence.":
    "활성 추천 상태, 선택된 종목군 편입, 직접적인 테마/사이클 증거가 유지되어야 합니다.",
  "Invalidate if recommendation score falls below 0.3500, cycle state weakens to correcting or structurally broken, or direct theme evidence is removed.":
    "추천 점수가 35.00% 아래로 떨어지거나, 사이클 상태가 조정/구조 훼손으로 약화되거나, 직접 테마 증거가 제거되면 투자 논리를 재검토합니다.",
  "AAPL security selection": "AAPL 종목 선택",
  "Apple Files Fiscal 2024 Form 10-K Annual Report": "Apple 2024 회계연도 Form 10-K 제출",
  "Annual report filed: Apple Inc.": "Apple Inc. 연간보고서 제출",
  "AAPL 2024 10-K annual reporting event": "AAPL 2024 10-K 연간 공시 이벤트",
  "AAPL 2024 Form 10-K source document": "AAPL 2024 Form 10-K 원천 문서",
  "AAPL outperformed SPY over measurement window": "AAPL이 측정 기간 동안 SPY를 상회했습니다.",
  "Access Policy Note": "접근 정책 메모",
  "Annual filing confirms continued services and installed-base revenue mix.":
    "연간 보고서가 서비스와 설치 기반 매출 구성이 계속 유지됨을 확인했습니다.",
  "default locked until explicit operator approval": "명시적 운영자 승인 전까지 기본 차단",
  "Annual Reporting": "연간 공시",
  "MARKET NEWS FLOW": "시장 뉴스 흐름",
  "US MARKET BREADTH": "미국 시장 참여도",
  "US Market Breadth": "미국 시장 참여도",
  "AI SEMICONDUCTOR CYCLE": "AI 반도체 사이클",
  "AI Semiconductor Cycle": "AI 반도체 사이클",
  "MACRO RATES FED": "금리·연준",
  "Macro Rates and Fed": "금리·연준",
  "ENERGY GEOPOLITICS": "에너지·지정학",
  "Energy Geopolitics": "에너지·지정학",
  "Annual reporting cadence driven by Form 10-K filings.": "Form 10-K 공시 주기로 확인하는 연간 공시 테마입니다.",
  "Annual reporting event quality remains supportive.": "연간 공시 이벤트 품질이 우호적으로 유지됩니다.",
  "Annual reporting quality": "연간 공시 품질",
  "AI output is stored as evidence metadata only; it does not place trades or mutate thesis state.":
    "AI 출력은 증거 메타데이터로만 저장되며, 거래를 실행하거나 투자 논리 상태를 바꾸지 않습니다.",
  "cycle, 가격, 이벤트, 품질 구성요소를 저장한다.":
    "사이클, 가격, 이벤트, 검증 항목을 저장합니다.",
  "BABA has no active thesis, so attribution coverage is incomplete.":
    "BABA에 활성 투자 논리가 없어 성과 귀속 커버리지가 불완전합니다.",
  "Business overview": "사업 개요",
  "Cash is visible so uninvested weight is not hidden inside attribution math.":
    "미투자 비중이 성과 귀속 계산 안에 숨지 않도록 현금을 명시합니다.",
  "Company overview and segment framing used to anchor the filing event to AAPL.":
    "공시 이벤트를 AAPL에 연결하기 위해 기업 개요와 사업 부문 맥락을 사용했습니다.",
  "Constructive cycle state is context for thesis quality, not an automatic buy signal.":
    "건설적인 사이클 상태는 투자 논리 품질의 맥락이지 자동 매수 신호가 아닙니다.",
  "Create or link an active long-term thesis before attribution can be trusted.":
    "성과 귀속을 신뢰하기 전에 활성 장기 투자 논리를 만들거나 연결해야 합니다.",
  "Create or link an active thesis before the next portfolio review.":
    "다음 포트폴리오 검토 전에 활성 투자 논리를 만들거나 연결해야 합니다.",
  "Review overweight exposure before any trade decision.":
    "거래 판단 전에 단일 종목 비중 초과 여부를 운영 검토로 확인해야 한다.",
  "Review target allocation before any trade decision.":
    "거래 판단 전에 목표 비중과 증액 필요성을 운영 검토로 확인해야 한다.",
  data_operations_artifact_runner: "데이터 운영 증거 관리",
  exit: "청산",
  exit_review: "청산 검토",
  exclude: "제외",
  sell: "매도",
  cycle_score: "사이클 점수",
  "cycle score": "사이클 점수",
  momentum_score: "모멘텀 점수",
  "momentum score": "모멘텀 점수",
  rank_score: "순위 점수",
  "rank score": "순위 점수",
  short_term_score: "단기 점수",
  "short term score": "단기 점수",
  macro_flow_score: "상위 흐름 점수",
  "macro flow score": "상위 흐름 점수",
  macro_flow_propagation: "상위 흐름 전파",
  macro_regime_score: "거시 사이클",
  "macro regime score": "거시 사이클",
  domain_cycle_score: "도메인 사이클",
  "domain cycle score": "도메인 사이클",
  theme_cycle_score: "테마 사이클",
  "theme cycle score": "테마 사이클",
  instrument_cycle_score: "종목 사이클",
  "instrument cycle score": "종목 사이클",
  cycle_conflict_penalty: "사이클 충돌 감점",
  "cycle conflict penalty": "사이클 충돌 감점",
  cycle_stack_context: "계층형 사이클 근거",
  fundamental_quality_score: "재무 품질",
  "fundamental quality score": "재무 품질",
  valuation_margin_score: "밸류에이션 여유",
  "valuation margin score": "밸류에이션 여유",
  peer_relative_score: "피어 비교",
  "peer relative score": "피어 비교",
  balance_sheet_risk_penalty: "재무 안정성",
  "balance sheet risk penalty": "재무 안정성",
  thesis_consistency_score: "투자 논리 일관성",
  "thesis consistency score": "투자 논리 일관성",
  fundamental_context: "기업 분석 근거",
  macro_regime: "거시",
  domain: "도메인",
  theme: "테마",
  instrument: "종목",
  conflict: "충돌",
  hierarchy: "계층 관계",
  macro_to_domain: "거시에서 도메인",
  macro_to_theme: "거시에서 테마",
  domain_to_theme: "도메인에서 테마",
  "Operating context used by the event extractor as a qualitative annual reporting signal.":
    "이벤트 추출기가 정성적 연간 공시 신호로 사용한 운영 맥락입니다.",
  "Management discussion": "경영진 논의",
  "Operating discussion used by the extractor to identify supportive annual reporting evidence.":
    "추출기가 우호적인 연간 공시 증거를 식별하는 데 사용한 운영 논의입니다.",
  "Portfolio positions have thesis/outcome coverage.": "포트폴리오 포지션에 투자 논리/성과 커버리지가 있습니다.",
  "Position-weighted alpha contribution for the covered AAPL thesis.":
    "커버된 AAPL 투자 논리에 대한 포지션 비중 가중 알파 기여입니다.",
  "Security and theme components are explanatory lenses, not additive totals.":
    "종목/테마 구성요소는 설명 관점이며 단순 합산 총액이 아닙니다.",
  "Some positions are excluded from attribution coverage.": "일부 포지션은 성과 귀속 커버리지에서 제외되었습니다.",
  "중장기 추천은 이후 성과 측정과 연결되어야 품질을 검토할 수 있다.":
    "중장기 추천은 이후 성과 측정과 연결되어야 판단을 검토할 수 있습니다.",
  "이 검토는 실제 주문이나 가상 주문을 만들지 않는 읽기 전용 품질 점검이다.":
    "이 검토는 실제 주문이나 가상 주문을 만들지 않는 읽기 전용 근거 점검입니다.",
  "Supporting event still carries human review gate before it can justify thesis mutation.":
    "보조 이벤트는 투자 논리 변경 근거로 쓰기 전에 AI 검증 조건을 통과해야 합니다.",
  "Theme lens mirrors the covered thesis exposure; do not add this to security lens as total P&L.":
    "테마 관점은 커버된 투자 논리 노출을 반영합니다. 이를 종목 관점과 합산해 총손익처럼 읽으면 안 됩니다.",
  "covered thesis and outcome remain valid": "커버된 투자 논리와 성과 측정이 계속 유효합니다.",
  "coverage status missing_thesis": "커버리지 상태: 투자 논리 누락",
  "quality_gate requires human review before this event can justify a thesis change.":
    "이 이벤트가 투자 논리 변경 근거가 되기 전에 품질 기준을 통과해야 합니다.",
  "quality_gate requires AI validator review before this event can justify a thesis change.":
    "이 이벤트가 투자 논리 변경 근거가 되기 전에 품질 기준을 통과해야 합니다.",
  "Review exit thesis and risk evidence; no trade automation is implied.":
    "청산 투자 논리와 리스크 증거를 검토해야 합니다. 자동 매매는 포함하지 않습니다.",
  "raw document delivery and access control are deferred until auth/RBAC exists":
    "원문 문서 제공과 접근 제어는 인증/RBAC가 준비될 때까지 보류됩니다.",
};

const EMBEDDED_LABEL_REPLACEMENTS: Array<[RegExp, string]> = [
  [
    /\b([A-Z0-9.-]+)\s+watch\s+thesis\s+via\s+US Market Breadth\b/g,
    "$1 관찰 투자 논리 · 근거 흐름: 미국 시장 참여도",
  ],
  [
    /\b([A-Z0-9.-]+)\s+watch\s+투자 논리\s+via\s+US Market Breadth\b/g,
    "$1 관찰 투자 논리 · 근거 흐름: 미국 시장 참여도",
  ],
  [
    /\b([A-Z0-9.-]+)\s+watch\s+thesis\s+via\s+Annual Reporting\b/g,
    "$1 관찰 투자 논리 · 근거 흐름: 연간 공시",
  ],
  [
    /\b([A-Z0-9.-]+)\s+watch\s+투자 논리\s+via\s+Annual Reporting\b/g,
    "$1 관찰 투자 논리 · 근거 흐름: 연간 공시",
  ],
  [
    /\b([A-Z0-9.-]+)\s+avoid\s+thesis\s+via\s+Annual Reporting\b/g,
    "$1 회피 투자 논리 · 근거 흐름: 연간 공시",
  ],
  [
    /\b([A-Z0-9.-]+)\s+avoid\s+투자 논리\s+via\s+Annual Reporting\b/g,
    "$1 회피 투자 논리 · 근거 흐름: 연간 공시",
  ],
  [
    /\bUS_MARKET_BREADTH flow propagated to ([A-Z0-9.-]+); sensitivity=positive; exposure=([0-9.]+); 이벤트=/g,
    "미국 시장 참여도 흐름이 $1에 우호적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [
    /\bUS_MARKET_BREADTH flow propagated to ([A-Z0-9.-]+); sensitivity=negative; exposure=([0-9.]+); 이벤트=/g,
    "미국 시장 참여도 흐름이 $1에 부정적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [
    /\bMACRO_RATES_FED flow propagated to ([A-Z0-9.-]+); sensitivity=negative; exposure=([0-9.]+); 이벤트=/g,
    "금리·연준 흐름이 $1에 부정적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [
    /\bMACRO_RATES_FED flow propagated to ([A-Z0-9.-]+); sensitivity=positive; exposure=([0-9.]+); 이벤트=/g,
    "금리·연준 흐름이 $1에 우호적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [
    /\bENERGY_GEOPOLITICS flow propagated to ([A-Z0-9.-]+); sensitivity=positive; exposure=([0-9.]+); 이벤트=/g,
    "에너지·지정학 흐름이 $1에 우호적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [
    /\bENERGY_GEOPOLITICS flow propagated to ([A-Z0-9.-]+); sensitivity=negative; exposure=([0-9.]+); 이벤트=/g,
    "에너지·지정학 흐름이 $1에 부정적으로 전파됐다. 노출도 $2. 근거=",
  ],
  [/\bQUANTUM_COMPUTING_POLICY\b/g, "양자컴퓨팅·정책 수혜"],
  [/\bUS Market Breadth\s+\(US Market Breadth\)/g, "미국 시장 참여도"],
  [/\bUS Market Breadth\s+\(미국 시장 참여도\)/g, "미국 시장 참여도"],
  [/\bUS Market Breadth\b/g, "미국 시장 참여도"],
  [/\bUS_MARKET_BREADTH\b/g, "미국 시장 참여도"],
  [/\bAI_SEMICONDUCTOR_CYCLE\b/g, "AI 반도체 사이클"],
  [/\bAI_LABOR_PRODUCTIVITY\b/g, "AI 도입·노동 영향"],
  [/\bENERGY_GEOPOLITICS\b/g, "에너지·지정학"],
  [/\bsupportive\b/g, "우호적"],
  [/\brisk_review\b/g, "리스크 검토"],
  [/\bwatch\b/g, "관찰"],
  [
    /\bRule-based free RSS enrichment; no paid provider or LLM used\.?;?/g,
    "무료 RSS 규칙으로 해석했다.",
  ],
  [
    /\bAI-validated RSS news 근거 via offline batch\.?/g,
    "배치 AI 검증을 통과한 RSS 뉴스 근거.",
  ],
  [
    /\bZero-weight financial quality component from normalized profitability, cash-flow quality, and peer context\.?/g,
    "정규화 수익성, 현금흐름 품질, 피어 맥락으로 만든 재무 품질 검증 항목.",
  ],
  [
    /\bZero-weight valuation margin component from valuation_snapshot margin-of-safety context\.?/g,
    "밸류에이션 스냅샷의 안전마진 맥락으로 만든 가격 매력 검증 항목.",
  ],
  [
    /\bZero-weight peer-relative component from peer percentile ranks\.?/g,
    "피어 그룹 내 백분위 순위로 만든 상대 비교 검증 항목.",
  ],
  [
    /\bZero-weight balance-sheet risk component; higher means lower observed leverage pressure\.?/g,
    "재무 안정성 검증 항목. 값이 높을수록 관측된 레버리지 부담이 낮다는 뜻이다.",
  ],
  [
    /\bZero-weight thesis consistency component\.?/g,
    "추천과 투자 논리의 일관성을 확인하는 검증 항목.",
  ],
  [/\bZero-weight\b/g, "총점 미반영"],
  [/\bzero-weight\b/g, "총점 미반영"],
  [/\bbase case\b/g, "기준 시나리오"],
  [/\bcontext\b/g, "근거 맥락"],
  [/\bmargin of safety\b/g, "안전마진"],
  [/\bneutral\b/g, "중립"],
  [/\brecommendation_id\b/g, "추천 ID"],
  [/\btotal_score\b/g, "총점"],
  [/\bvaluation_margin_score\b/g, "밸류에이션 여유 점수"],
  [/\bvaluation_snapshot\b/g, "밸류에이션 스냅샷"],
  [/\bvaluations\b/g, "밸류에이션 입력"],
  [
    /\bLatest hierarchical macro-regime 사이클 score connected to the theme path\.?/g,
    "테마 경로에 연결된 최신 계층형 거시 사이클 점수.",
  ],
  [
    /\bLatest hierarchical theme 사이클 score for the linked 추천 theme\.?/g,
    "연결된 추천 테마의 최신 계층형 테마 사이클 점수.",
  ],
  [/\bSelected 추천 node:\s*/g, "선택한 추천 흐름: "],
  [
    /\bThesis id:\s*none,\s*status:\s*missing,\s*invalidation conditions present:\s*false\.?/g,
    "연결된 투자 논리는 아직 없고, 무효화 조건도 확인되지 않았다.",
  ],
  [
    /\bActive instrument with ([0-9]+) price observations through ([0-9-]+)\.?/g,
    "$2까지 가격 관측치 $1개가 있는 활성 종목이다.",
  ],
  [/\bReturn Since First Observation\b/g, "관측 시작 이후 수익률"],
  [/\bOne Day Return\b/g, "1일 수익률"],
  [/\bequity-research-artifact-[0-9]+\b/g, "기업 리서치 결과 연결됨"],
  [/\bbuy_candidate\b/g, "매수 판단 항목"],
  [/\bmacro-flow\b/g, "상위 흐름"],
  [/\bperformance window\b/g, "성과 측정창"],
  [/성과 window/g, "성과 측정창"],
  [/\bcatalyst\b/g, "촉매"],
  [/\brisk\b/g, "리스크"],
  [/\binvalidation condition\b/g, "무효화 조건"],
  [/\bSource runs\b/g, "원천 실행"],
  [/\bSource run\b/g, "원천 실행"],
  [/\bLatest financial period\b/g, "최근 재무 기간"],
  [/\bValuation methods\b/g, "밸류에이션 방식"],
  [/\bRationale:/g, "해석:"],
  [/\bEvidence:/g, "근거:"],
  [/검색\/RAG 확인용 문서 조각/g, "원문 근거"],
  [/검색\/RAG에 사용할 문서 청크/g, "원문 근거"],
  [/가상 거래\(Paper\)/g, "가상 거래"],
  [/\bexposure_rationale=/g, "노출 근거: "],
  [/\bsensitivity=positive;?/g, "민감도: 우호."],
  [/\bsensitivity=negative;?/g, "민감도: 부정."],
  [/\bsensitivity=neutral;?/g, "민감도: 중립."],
  [/\bexposure=([0-9.]+);?/g, "노출도 $1."],
  [/\bret; /g, ""],
  [/\bBroad market ETF maps directly to US market breadth\.?/g, "광범위 시장 ETF라 미국 시장 참여도 흐름에 직접 노출된다."],
  [/\bHigh-beta equity tends to be sensitive to broad market risk appetite\.?/g, "고베타 성장주는 시장 위험선호 변화에 민감하다."],
  [/\bBroad US equities usually de-rate when rate expectations rise\.?/g, "미국 광범위 주식은 금리 기대가 높아질 때 밸류에이션 압력을 받기 쉽다."],
  [
    /\bAnalysis is limited to the RSS title, metadata, and retrieval context\.?/g,
    "분석은 RSS 제목, 메타데이터, 저장된 검색 맥락만 사용했습니다.",
  ],
  [
    /\bNo article body, yield level, gold price, or fiscal-policy details were provided\.?/g,
    "기사 본문, 금리 수준, 금 가격, 재정정책 세부 정보는 제공되지 않았습니다.",
  ],
  [/\brecommendation score falls below 0\.3500\b/g, "추천 점수가 0.3500 아래로 하락"],
  [/\brecommendation\b/g, "추천"],
  [/\bcycle state\b/g, "사이클 상태"],
  [/\bcycle\b/g, "사이클"],
  [/\bfeature provenance\b/g, "가격 지표 출처"],
  [/\bfeature snapshot\b/g, "가격 지표 기록"],
  [/\bmarket-feature\b/g, "가격 지표"],
  [/\brank component\b/g, "순위 항목"],
  [/\bsource run\b/g, "원천 실행"],
  [/\bscore component evidence_id\b/g, "점수 항목 근거"],
  [/\bevidence_id\b/g, "근거 ID"],
  [/\bsource_run_id\b/g, "수집·계산 실행 번호"],
  [/\bcomponent\b/g, "구성요소"],
  [/\bz-score\b/g, "표준화 점수"],
  [/\brank\b/g, "순위"],
  [/\bevent\b/g, "이벤트"],
  [/\bfeature\b/g, "가격 지표"],
  [/\bevidence\b/g, "근거"],
  [/\boutcome\b/g, "성과"],
  [/\breview\b/g, "검토"],
  [/\bread-only\b/g, "읽기 전용"],
  [/\bbroker boundary\b/g, "증권사 연결 상태"],
  [/\bbroker submit\b/g, "증권사 주문 제출"],
  [/\bpaper validation and order boundary\b/g, "가상 매매 검증과 실거래 상태"],
  [/\bpaper validation\b/g, "가상 매매 검증"],
  [/\bkill switch\b/g, "킬 스위치"],
  [/\bthesis\b/g, "투자 논리"],
  [/\bThesis\b/g, "투자 논리"],
  [/\bweight\b/g, "가중치"],
  [/\baction\b/g, "조치"],
  [/\blong_term_core\b/g, "장기 핵심 전략"],
  [/\bANNUAL_REPORTING\b/g, "연간 공시"],
  [/\bAnnual Reporting\b/g, "연간 공시"],
  [/\bBROAD_US_EQUITY\b/g, "미국 광범위 주식"],
  [/\bBroad US Equity\b/g, "미국 광범위 주식"],
  [/\baccumulate_candidate\b/g, "분할 매수 판단 항목"],
  [/\bconfirming\b/g, "확인 국면"],
  [/\bcredential-free news flow\b/g, "무료 출처 기반 뉴스 흐름"],
  [/\bcurrent_event_impacts\b/g, "현재 이벤트 영향"],
  [/\bMACRO_RATES_FED\b/g, "금리·연준"],
  [/\bMARKET_NEWS_FLOW\b/g, "시장 뉴스 흐름"],
  [/\bactive\b/g, "활성"],
  [/\bforming\b/g, "형성 중"],
  [/\bcorrecting\b/g, "조정 중"],
  [/\bstructurally_broken\b/g, "구조 훼손"],
  [/\bstructurally broken\b/g, "구조 훼손"],
  [/\bunavailable\b/g, "없음"],
  [/\bmarket feature\b/g, "가격 지표"],
  [/\bmarket features\b/g, "가격 지표"],
  [/\bbootstrap-v1\b/g, "초기화 v1"],
  [/\bfixture-v1\b/g, "검증용 v1"],
  [/연간 공시\s*\(연간 공시\)/g, "연간 공시"],
  [/장기 핵심 전략 전략/g, "장기 핵심 전략"],
  [/가격 가격 지표 출처/g, "가격 지표 출처"],
  [/성과을/g, "성과를"],
  [/투자 투자 논리/g, "투자 논리"],
  [/핵심 thesis/g, "핵심 투자 논리"],
  [/좋은 thesis/g, "좋은 투자 논리"],
  [/thesis review/g, "투자 논리 검토"],
  [/thesis는/g, "투자 논리는"],
  [/밸류에이션 스냅샷가/g, "밸류에이션 스냅샷이"],
  [/안전마진 안전마진/g, "안전마진"],
  [/미국 시장 참여도\s+\(미국 시장 참여도\)/g, "미국 시장 참여도"],
  [/우호적로/g, "우호적으로"],
  [/부정적로/g, "부정적으로"],
  [/ai-근거/g, "AI 근거"],
  [/없음 상태/g, "없는 상태"],
];

function translateEmbeddedLabels(value: string): string {
  const translated = EMBEDDED_LABEL_REPLACEMENTS.reduce(
    (translated, [pattern, replacement]) => translated.replace(pattern, replacement),
    value,
  );
  return translated
    .replace(/좋은 thesis/g, "좋은 투자 논리")
    .replace(/thesis review/g, "투자 논리 검토")
    .replace(/thesis(?=[가-힣])/g, "투자 논리")
    .replace(/안전마진\s+안전마진/g, "안전마진")
    .replace(/밸류에이션 스냅샷가/g, "밸류에이션 스냅샷이");
}

export function koLabel(value: string | null | undefined): string {
  if (!value) {
    return "없음";
  }
  return KOREAN_LABELS[value] ?? translateEmbeddedLabels(value);
}

export function koCode(value: string | null | undefined): string {
  if (!value) {
    return "없음";
  }
  const lowerValue = value.toLowerCase();
  const spacedValue = value.replaceAll("_", " ");
  return KOREAN_LABELS[value] ?? KOREAN_LABELS[lowerValue] ?? KOREAN_LABELS[spacedValue] ?? spacedValue;
}

export function koReason(value: string | null | undefined): string {
  if (!value) {
    return "없음";
  }
  const skippedSameWeight = value.match(/^skipped:([A-Z0-9.-]+)\.target weight equals current weight$/);
  if (skippedSameWeight) {
    return `${skippedSameWeight[1]}은 현재 비중과 목표 비중이 같아 가상 조치가 생략됐다.`;
  }
  const portfolioReason = value.match(
    /^([A-Z0-9.-]+) portfolio review action ([^.]+)\. Thesis review action ([^;]+); current weight ([^;]+); recommended weight ([^;]+); coverage status ([^;.]+)(?:; single position review cap ([0-9.]+))?\.$/,
  );
  if (portfolioReason) {
    const [, symbol, action, thesisAction, currentWeight, recommendedWeight, coverageStatus, singlePositionCap] =
      portfolioReason;
    const translatedReason = [
      `${symbol} 포트폴리오 검토 조치: ${koCode(action)}.`,
      `투자 논리 검토 조치: ${koCode(thesisAction)}.`,
      `현재 비중: ${currentWeight}.`,
      `권장 비중: ${koCode(recommendedWeight)}.`,
      `커버리지 상태: ${koCode(coverageStatus)}.`,
    ];
    if (singlePositionCap) {
      translatedReason.push(`단일 종목 검토 기준: ${singlePositionCap}.`);
    }
    return translatedReason.join(" ");
  }
  return koLabel(value);
}

const BLOCKED_REASON_DETAILS: Record<string, { title: string; description: string; nextStep: string }> = {
  account_daily_notional_limit_exceeded: {
    title: "계좌 일일 주문 한도를 넘는다",
    description: "오늘 누적 주문 후보와 이번 주문 후보를 합치면 계좌의 일일 금액 한도를 초과한다.",
    nextStep: "오늘 실행 후보를 줄이거나, 별도 승인 절차를 거쳐 가상 거래 한도 정책을 조정한다.",
  },
  account_order_notional_limit_exceeded: {
    title: "계좌 단일 주문 한도를 넘는다",
    description: "이 후보 한 건의 주문 금액이 가상 거래 계좌에 설정된 단일 주문 한도보다 크다.",
    nextStep: "목표 비중까지 한 번에 처리하지 말고 여러 가상 거래 단계로 쪼갠다.",
  },
  account_permission_not_active: {
    title: "계좌 권한이 활성 상태가 아니다",
    description: "가상 거래 권한이 활성 상태가 아니면 주문 의도 평가도 통과시킬 수 없다.",
    nextStep: "가상 거래 계좌 권한을 활성 상태로 등록한다.",
  },
  account_permission_scope_insufficient: {
    title: "계좌 권한 범위가 부족하다",
    description: "현재 권한이 읽기 전용이거나 가상 매매 평가에 필요한 범위보다 낮다.",
    nextStep: "가상 매매 전용 계좌에 가상 매매 권한을 부여한다.",
  },
  broker_boundary_not_enabled: {
    title: "증권사 연결 상태가 활성화되지 않았다",
    description: "실제 주문 전송이 아니더라도 가상 주문 미리보기 상태가 활성이어야 한다.",
    nextStep: "가상 매매용 증권사 연결 상태를 활성으로 등록한다.",
  },
  broker_preview_not_supported: {
    title: "주문 미리보기가 꺼져 있다",
    description: "가상 매매 단계에서는 실제 제출이 아니라 미리보기 평가 기능만 필요하다.",
    nextStep: "가상 매매용 증권사 연결에서 주문 미리보기를 켠다.",
  },
  human_approval_required: {
    title: "거래 안전 승인이 아직 없다",
    description: "AI 검증이 통과해도 실거래 상태, 한도, 킬 스위치가 통과하지 않으면 거래 후보는 승인되지 않는다.",
    nextStep: "AI 검증 근거와 안전 조건을 확인한 뒤 거래 안전 승인 기록을 남긴다.",
  },
  kill_switch_engaged: {
    title: "킬 스위치가 차단 중이다",
    description: "킬 스위치가 켜져 있으면 가상 매매 후보도 주문 의도 승인 상태로 넘어가지 않는다.",
    nextStep: "실거래 전에는 유지한다. 가상 검증만 열 때도 별도 승인 기록이 필요하다.",
  },
  order_limit_policy_not_active: {
    title: "주문 한도 정책이 비활성이다",
    description: "단일 주문, 일일 주문, 비중 변화, 현금 버퍼 한도가 활성 상태로 설정되어야 한다.",
    nextStep: "장기 가상 포트폴리오용 한도 정책을 활성 상태로 등록한다.",
  },
  position_recommendation_conflict: {
    title: "보유와 추천이 충돌한다",
    description: "현재 보유 중인 종목이 최신 추천에서는 제외/매도 후보로 분류됐다.",
    nextStep: "AI 자동 검토가 투자 논리와 최신 근거를 대조해 유지, 감액, 청산 중 하나의 후보로 분류한다.",
  },
  portfolio_risk_budget_guardrail: {
    title: "포트폴리오 위험 예산이 막고 있다",
    description: "단일 종목, 섹터, 테마 집중도 중 하나가 한도를 넘어서 가상 검증 입력으로 쓰지 않는다.",
    nextStep: "포트폴리오 커버리지 화면에서 초과 종목과 초과 섹터·테마를 먼저 확인한다.",
  },
  blocked_by_risk_budget_review: {
    title: "위험 예산 검토가 필요하다",
    description: "포트폴리오 위험 예산 검증 작업이 이 포트폴리오를 검토 필요 상태로 판단했다.",
    nextStep: "초과 비중, 초과 섹터, 초과 테마를 줄일지 또는 투자 논리를 보강할지 검토한다.",
  },
  over_single_position_limit: {
    title: "단일 종목 비중이 너무 크다",
    description: "한 종목의 포트폴리오 비중이 장기 포트폴리오의 단일 종목 한도를 넘었다.",
    nextStep: "해당 종목의 thesis, 세금/비용, 대체 후보를 확인한 뒤 축소 여부를 검토한다.",
  },
  sector_over_limit: {
    title: "섹터 집중도가 너무 높다",
    description: "같은 섹터에 묶인 보유 비중이 위험 예산의 섹터 한도를 넘었다.",
    nextStep: "같은 섹터 안에서 중복된 베팅인지, 분산이 필요한지 확인한다.",
  },
  theme_over_limit: {
    title: "테마 집중도가 너무 높다",
    description: "같은 거시·테마 흐름에 묶인 보유 비중이 테마 한도를 넘었다.",
    nextStep: "해당 테마가 아직 유효한지, 상위 사이클과 충돌하지 않는지 확인한다.",
  },
  missing_portfolio_risk_budget_guardrail: {
    title: "위험 예산 검증이 아직 없다",
    description: "최신 포트폴리오 위험 예산 검증 결과가 없어 가상 검증 입력으로 쓰기 어렵다.",
    nextStep: "portfolio-risk-budget-guardrail-run을 실행한 뒤 paper validation을 다시 실행한다.",
  },
  single_order_notional_limit_exceeded: {
    title: "단일 주문 금액 한도를 넘는다",
    description: "목표 비중까지 한 번에 이동하면 가상 거래 주문 한도보다 주문 금액이 커진다.",
    nextStep: "한도 안에서 1차 감액/증액 후보로 쪼개고 다음 스냅샷에서 재검증한다.",
  },
  single_order_weight_delta_limit_exceeded: {
    title: "한 번에 바꾸는 비중이 너무 크다",
    description: "현재 비중에서 목표 비중까지의 변화 폭이 단일 주문 비중 변화 한도를 넘는다.",
    nextStep: "목표 비중으로 바로 가지 말고 허용된 비중 변화 폭 안에서 단계적으로 조정한다.",
  },
  symbol_not_allowed_for_account: {
    title: "계좌에서 허용된 종목이 아니다",
    description: "가상 거래 계좌의 허용 종목 목록이 이 종목을 허용하지 않는다.",
    nextStep: "허용 종목 목록을 검토하고 가상 거래 계좌 범위에 포함할지 결정한다.",
  },
};

export type KoreanBlockedReason = {
  raw: string;
  symbol: string | null;
  code: string;
  title: string;
  description: string;
  nextStep: string;
};

export function koBlockedReason(value: string): KoreanBlockedReason {
  const riskGateMatch = value.match(/^portfolio_risk_budget_guardrail:([a-z0-9_:-]+)$/);
  if (riskGateMatch) {
    const code = riskGateMatch[1];
    const detail = BLOCKED_REASON_DETAILS[code] ?? BLOCKED_REASON_DETAILS.portfolio_risk_budget_guardrail;
    return {
      raw: value,
      symbol: null,
      code,
      title: detail.title,
      description: detail.description,
      nextStep: detail.nextStep,
    };
  }

  const riskBlockerMatch = value.match(/^portfolio_risk_budget_guardrail_blocker:([a-z0-9_:-]+)$/);
  if (riskBlockerMatch) {
    const code = riskBlockerMatch[1];
    const detail = BLOCKED_REASON_DETAILS[code];
    return {
      raw: value,
      symbol: null,
      code,
      title: detail?.title ?? koCode(code),
      description: detail?.description ?? "포트폴리오 위험 예산 검증 작업이 남긴 차단 사유다.",
      nextStep: detail?.nextStep ?? "포트폴리오 커버리지 화면에서 해당 위험 예산 항목을 확인한다.",
    };
  }

  const conflictMatch = value.match(/^position_recommendation_conflict:([A-Z0-9.-]+)$/);
  if (conflictMatch) {
    const code = "position_recommendation_conflict";
    const detail = BLOCKED_REASON_DETAILS[code];
    return {
      raw: value,
      symbol: conflictMatch[1],
      code,
      title: detail.title,
      description: detail.description,
      nextStep: detail.nextStep,
    };
  }

  const symbolMatch = value.match(/^([A-Z0-9.-]+):([a-z0-9_:-]+)$/);
  const symbol = symbolMatch ? symbolMatch[1] : null;
  const code = symbolMatch ? symbolMatch[2] : value;
  const detail = BLOCKED_REASON_DETAILS[code];
  return {
    raw: value,
    symbol,
    code,
    title: detail?.title ?? koCode(code),
    description: detail?.description ?? "아직 상세 설명이 없는 차단 사유다. 원문 reason code를 기준으로 검토해야 한다.",
    nextStep: detail?.nextStep ?? "차단 사유를 운영 문서에 추가하고, AI 자동 검토 후 다음 조치를 결정한다.",
  };
}

export function koBoolean(value: boolean): string {
  return value ? "예" : "아니오";
}
